# Generated by Django 3.1.3 on 2020-11-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=300)),
                ('discription', models.TextField(max_length=600)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
