# Generated by Django 3.1.3 on 2020-11-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discription',
            field=models.TextField(max_length=300),
        ),
    ]
