# Generated by Django 3.1.3 on 2020-11-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201116_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discription',
            field=models.CharField(max_length=150),
        ),
    ]
